ThatForumCMS/Models/Category/CategoryListItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ThatForumCMS.Models.Category {
    public class CategoryListItemViewModel {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? ParentCategoryId { get; set; }
    }
}

ThatForumCMS/Models/Category/CreateCategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ThatForumCMS.Models.Category {
    public class CreateCategoryViewModel {
        public int Id { get; set; }
        //[MinLength(3)]
        [StringLength(100, ErrorMessage = "The category name should be at least 3 characters", MinimumLength = 3)]
        public string Name { get; set; }
        [Display(Name = "Parent Category")]
        public int? ParentCategoryId { get; set; }
        //[Display(Name = "Parent Category")]
        public IEnumerable<SelectListItem> ExistingCategories { get; set; }
    }
}

ThatForumCMS/Models/Category/DeleteCategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ThatForumCMS.Models.Category {
    public class DeleteCategoryViewModel {
        public int Id { get; set; }
        public string Name { get; set; }
        [Display(Name = "Subcategories number")]
        public int ChildCategoriesNum { get; set; }
        [Display(Name = "Delete also all sub-categories")]
        public bool DeleteAllChildCategories { get; set; }
        /// <summary>
        /// if false, they will be placed directly to the parent category.
        /// if no parent category, there will be error - can't delete posts
        /// </summary>
        [Display(Name = "Delete also all category's topics")]
        public bool DeleteAllCategoryTopics { get; set; }
    }
}

ThatForumCMS/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ThatForumCMS.BL.Interfaces;
using AutoMapper;
using ThatForumCMS.BL.EntitiesDTO;
using ThatForumCMS.Models.Category;
using ThatForumCMS.Util;
using ThatForumCMS.Infrastructure;
using ThatForumCMS.Models;
using Microsoft.AspNet.Identity.Owin;

namespace ThatForumCMS.Controllers
{
    [AuthorizeInAnyRole(ForumUserRoles.SuperAdmin, ForumUserRoles.Admin)]
    public class CategoryController : Controller
    {
        private ICategoryService categoryService;
        private ITopicService topicService;
        private IPostService postService;
        private int ownTopicsOnPage = 5;
        private int subCategorysTopicsOnPage = 2;
        private IUserService UserService {
            get {
                return HttpContext.GetOwinContext().GetUserManager<IUserService>();
            }
        }

        public CategoryController(ICategoryService categoryService, ITopicService topicService, IPostService postService) {
            this.categoryService = categoryService;
            this.topicService = topicService;
            this.postService = postService;
        }


        // GET: Category - show all categories lists
        public ActionResult Index()
        {
            var allCategsDTO = categoryService.GetAllCategories();
            var model = Mapper.Map<IEnumerable<CategoryDTO>, List<CategoryListItemViewModel>>(allCategsDTO);
            
            return View(model);
        }

        // GET: Category/View/5
        [AllowAnonymous]
        public ActionResult View(int? id)
        {
            string noCategMsg = "No such category exists";
            if (!id.HasValue) {
                return new HttpStatusCodeResult(404, noCategMsg);
            }
            var entityID = id.Value;


            var categ = categoryService.GetCategoryById(entityID);
            if (categ == null) {
                return new HttpStatusCodeResult(404, "No such category exists");
            }

            var childCategDTOs = categoryService.GetChildCategories(entityID);

            CategoryIndexViewModel categoryViewModels = new CategoryIndexViewModel();
            categoryViewModels.Id = entityID;
            categoryViewModels.Name = categ.Name;
            categoryViewModels.Topics = CategoryUtils.GetTopicBadgeViewModels(topicService, UserService, postService, entityID, ownTopicsOnPage);

            // for each category get subcategories and their own topics
            var subCategories = categoryService.GetChildCategories(entityID);
            var tempSubCategoryIndexVMs = new List<CategoryIndexViewModel>();
            foreach (var subCategory in subCategories) {
                var subCategoryViewModels = new CategoryIndexViewModel();
                subCategoryViewModels = Mapper.Map<CategoryDTO, CategoryIndexViewModel>(subCategory);
                subCategoryViewModels.Topics = CategoryUtils.GetTopicBadgeViewModels(topicService, UserService, postService, subCategory.Id, subCategorysTopicsOnPage);

                tempSubCategoryIndexVMs.Add(subCategoryViewModels);
            }
            categoryViewModels.ChildCategories = tempSubCategoryIndexVMs;


            return View(categoryViewModels);
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            var model = new CreateCategoryViewModel();
            CategoryUtils util = new CategoryUtils();
            var categoriesDTOs = categoryService.GetAllParentCategories();
            model.ExistingCategories = CategoryUtils.GetCategoriesListItems(categoriesDTOs);

            return View(model);
        }

        // POST: Category/Create
        [HttpPost]
        public ActionResult Create(CreateCategoryViewModel model)
        {
            try
            {
                if (ModelState.IsValid) {
                    var categDTO = Mapper.Map<CreateCategoryViewModel, CategoryDTO>(model);
                    categoryService.Create(categDTO);
                } else {
                    return View();
                }

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("Error", ex);
                return View();
            }
        }

        // GET: Category/Edit/5
        public ActionResult Edit(int? id)
        {
            string noCategMsg = "No such category exists";
            if (!id.HasValue) {
                return new HttpStatusCodeResult(404, noCategMsg);
            }
            var entityID = id.Value;

            CreateCategoryViewModel model;
            try {
                var categoryDTO = categoryService.GetCategoryById(entityID);
                model = Mapper.Map<CategoryDTO, CreateCategoryViewModel>(categoryDTO);
                var categoriesDTOs = categoryService.GetAllParentCategories().Where(c => c.Id != entityID);
                model.ExistingCategories = CategoryUtils.GetCategoriesListItems(categoriesDTOs);
            }
            catch (Exception) {
                return new HttpStatusCodeResult(500, "Something went wrong");
            }
            

            return View(model);
        }

        // POST: Category/Edit/5
        [HttpPost]
        public ActionResult Edit(CreateCategoryViewModel model)
        {
            try {
                if (ModelState.IsValid) {
                    var categDTO = Mapper.Map<CreateCategoryViewModel, CategoryDTO>(model);
                    categoryService.Update(categDTO);
                } else {
                    
                    return View(model);
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex) {
                ModelState.AddModelError("Error", ex);
                return View(model);
            }
        }


        [HttpPost]
        public string EditAjax(CreateCategoryViewModel model) {
            try {
                if (ModelState.IsValid) {
                    if (string.IsNullOrWhiteSpace(model.Name)) {
                        return "The category name can't be empty";
                    }
                    var categDTO = Mapper.Map<CreateCategoryViewModel, CategoryDTO>(model);
                    categoryService.Update(categDTO);
                } else {
                    return "The data you entered isn't valid. " + ModelState.Select(x => x.Value.Errors)
                           .Where(y => y.Count > 0)
                           .ToList().FirstOrDefault().FirstOrDefault().ErrorMessage;
                }

                return "Done!";
            }
            catch (Exception ex) {
                return "The data you entered isn't valid.";
            }
        }

        // GET: Category/Delete/5
        public ActionResult Delete(int? id)
        {
            string noCategMsg = "No such category exists";
            if (!id.HasValue) {
                return new HttpStatusCodeResult(404, noCategMsg);
            }
            var entityID = id.Value;

            try {
                var categDTO = categoryService.GetCategoryInfoForDeletion(entityID);
                var model = Mapper.Map<DeleteCategoryDTO, DeleteCategoryViewModel>(categDTO);

                return View(model);
            }
            catch (Exception) {
                return new HttpStatusCodeResult(500, "Something went wrong");
            }
            
        }

        // POST: Category/Delete/5
        [HttpPost]
        public ActionResult Delete(DeleteCategoryViewModel model)
        {
            try
            {
                if (ModelState.IsValid) {
                    var deleteCategoryDTO = Mapper.Map<DeleteCategoryViewModel, DeleteCategoryDTO>(model);

                    int childCategoriesNum = categoryService.GetCategoryChildNumber(model.Id);
                    if (childCategoriesNum > 0 && !model.DeleteAllChildCategories) {
                        ModelState.AddModelError("Error", "Can't delete category while child categories exists. Move child categories " +
                            "to other parent category, or make them parent category. But in case if you want to delete also all " +
                            "child categories set corresponding checkbox");
                        model.ChildCategoriesNum = childCategoriesNum;
                        return View(model);
                    }

                    categoryService.Delete(deleteCategoryDTO);//also deletes child categories if correcponding field is set to true

                } else {
                    return View(model);
                }
                
                return RedirectToAction("Index");
            }
            catch
            {
                throw;
                //return View();
            }
        }
        
    }
}

ThatForumCMS/Views/Category/Create.cshtml
@model ThatForumCMS.Models.Category.CreateCategoryViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Category", FormMethod.Post, new { @id = "categoryCreateForm" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CreateCategoryViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (Model.ExistingCategories != null) {
            <div class="form-group">
                @Html.LabelFor(model => model.ParentCategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ParentCategoryId", Model.ExistingCategories, "Parent Category", new { @class = "form-control" })
                </div>
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryvalidation")
@Scripts.Render("~/bundles/validationCategoryName")
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ThatForumCMS/Views/Category/Delete.cshtml
@model ThatForumCMS.Models.Category.DeleteCategoryViewModel

@{
    ViewBag.Title = "Delete category";
}

<h2>Delete category</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })*@
                @Model.Name
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChildCategoriesNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.LabelFor(model => model.ChildCategoriesNum, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.Label(Model.ChildCategoriesNum.ToString())
            </div>
        </div>
        @if (Model.ChildCategoriesNum > 0) {
            <div class="form-group">
                @Html.LabelFor(model => model.DeleteAllChildCategories, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.DeleteAllChildCategories)
                        @Html.ValidationMessageFor(model => model.DeleteAllChildCategories, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        }
        

        <div class="form-group">
            @Html.LabelFor(model => model.DeleteAllCategoryTopics, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.DeleteAllCategoryTopics)
                    @Html.ValidationMessageFor(model => model.DeleteAllCategoryTopics, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Delete" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ThatForumCMS/Views/Category/Edit.cshtml
@model ThatForumCMS.Models.Category.CreateCategoryViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit category</h2>

<div id="savingresult"></div>
@*@using (Html.BeginForm("Edit", "Category", FormMethod.Post, new { @id = "categoryCreateForm" }))*@
@using (Ajax.BeginForm("EditAjax", "Category", new AjaxOptions
{
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "savingresult",
    LoadingElementId = "loader"
},new { @id = "categoryCreateForm" })) {
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (Model.ExistingCategories != null) {
            <div class="form-group">
                @Html.LabelFor(model => model.ParentCategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ParentCategoryId", Model.ExistingCategories, "Parent Category(if needed)", new { @class = "form-control" })
                </div>
            </div>
        }
        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
    <div id="loader" class=" aletr" style="display:none">
        Loading...<img src="~/Content/Default/ajax-loader.gif" />
    </div>
}

@Scripts.Render("~/bundles/jqueryvalidation")
@Scripts.Render("~/bundles/validationCategoryName")

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ThatForumCMS/Views/Category/Index.cshtml
@model IEnumerable<ThatForumCMS.Models.Category.CategoryListItemViewModel>

@{
    ViewBag.Title = "Manage categories";
}

<h2>Manage categories</h2>

<p>
    @Html.ActionLink("Create New", "Create","Category", new { @class = "btn btn-primary" })
</p>
<table class="table table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        if (item.ParentCategoryId == null) {
            <tr>
                <td>
                    <strong>
                        @Html.DisplayFor(modelItem => item.Name)
                    </strong>
                </td>
                <td>
                    @Html.Partial("CategoryControlBtns", item.Id)
                </td>
            </tr>

            foreach (var categ in Model) {// table-striped table-hoverdisplay subcategories

                if (categ.ParentCategoryId == item.Id) {
                    <tr>
                        <td>
                            <div>-- @Html.DisplayFor(modelItem => categ.Name)</div>
                        </td>
                        <td>
                            @Html.Partial("CategoryControlBtns", categ.Id)
                        </td>
                    </tr>
                }

            }

        }
    }

</table>

ThatForumCMS/Views/Category/View.cshtml
@model ThatForumCMS.Models.CategoryIndexViewModel


@if (Model == null) {
    return;
}
<hr/>
@Html.ActionLink("Create topic", "Create", "Topic", null, new { @class = "btn btn-primary" })
<hr />

  <div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">
            @Html.ActionLink(Model.Name, "View", "Category", new { id = Model.Id }, null)
        </h3>
    </div>

    <!-- Show subcategories and their topics first-->
    @foreach (var subCategoryIndex in Model.ChildCategories) {
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title">
                    @Html.ActionLink(subCategoryIndex.Name, "View", "Category", new { id = subCategoryIndex.Id }, null)
                </h3>
            </div>
            @Html.ShowCategoriesTopicsIndex(subCategoryIndex.Topics)

        </div>
        <!-- subcategory' topics-->

    }

    @Html.ShowCategoriesTopicsIndex(Model.Topics)
    <!-- Parent category topics -->
</div>