ThatForumCMS/Controllers/TopicController.cs
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ThatForumCMS.BL.Interfaces;
using ThatForumCMS.Models.Topic;
using ThatForumCMS.Util;
using AutoMapper;
using ThatForumCMS.BL.EntitiesDTO;
using ThatForumCMS.Infrastructure;
using ThatForumCMS.Models;
using System.Drawing;
using System.Drawing.Drawing2D;
using ThatForumCMS.Models.Post;

namespace ThatForumCMS.Controllers
{
    //[Authorize]
    public class TopicController : Controller
    {
        #region Properties and fields
        private ICategoryService categoryService;
        private ITopicService topicService;
        private IPostService postService;
        private IUserProfileService userProfileService;
        private IErrorLoggerService errorLogger;
        private int postsPerPage = 3;
        private int topicsPerPageAtModerationPage = 3;
        private IUserService UserService {
            get {
                return HttpContext.GetOwinContext().GetUserManager<IUserService>();
            }
        }
        private IAuthenticationManager AuthenticationManager {
            get {
                return HttpContext.GetOwinContext().Authentication;
            }
        }
        #endregion

        public TopicController(ITopicService topicService, ICategoryService categoryService, IPostService postService, 
            IErrorLoggerService errorLogger, IUserProfileService userProfileService) {

            this.topicService = topicService;
            this.categoryService = categoryService;
            this.postService = postService;
            this.errorLogger = errorLogger;
            this.userProfileService = userProfileService;
        }

        // GET: Topic
        public ActionResult Index() {
            return RedirectToAction("Index", "Home");
        }

        // GET: Topic/View/5
        public ActionResult View(int? id, int page = 1) {

            string noTopicMsg = "No such topic exists";
            if (!id.HasValue) {
                return new HttpStatusCodeResult(404, noTopicMsg);
            }
            var entityID = id.Value;


            var topicDTO = topicService.GetTopic(entityID);
            if(topicDTO == null) {
                string msg = "No such topic exists";
                //errorLogger.Log(msg, priority: 10, exception: ex);
                return new HttpStatusCodeResult(404, msg);
            }

            var topicPageViewModel = Mapper.Map<TopicDTO, TopicPageViewModel>(topicDTO);
            
            var postDTOs = postService.GetTopicPostsOrderedByDate(entityID, postsPerPage, (page - 1) * postsPerPage);

            if(postDTOs == null) {
                string msg = "Something went wrong";
                errorLogger.Log("Can't get posts in topic", priority: 7, url: "Topic/View/"+ entityID + "?page="+page);
                return new HttpStatusCodeResult(500, msg);
            }

            topicPageViewModel.Posts = Mapper.Map<IEnumerable<PostDTO>, List<TopicsPostViewModel>>(postDTOs);
            foreach (var item in topicPageViewModel.Posts) {

                var user = UserService.GetUserNameByUserProfileId(item.UserProfileId);

                if (string.IsNullOrEmpty(user)) {
                    string msg = "Something went wrong";
                    return new HttpStatusCodeResult(500, msg);
                }
                item.Author = user;
                item.AvatarUrl = userProfileService.GetAvatarUrl(item.UserProfileId);
                item.Signature = userProfileService.GetUserProfileSignature(item.UserProfileId);
            }
            // check if author field filed
            topicPageViewModel.PagingInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = postsPerPage,
                TotalItems = postService.GetTopicsTotalPostsNumber(entityID)
            };

            try {
                topicService.AddViewToTopic(entityID);
            }
            catch (Exception ex) {
                string msg = "Something went wrong";
                errorLogger.Log("Add +1 view topic didn't happened since no such topic exists", priority: 10, exception: ex);
                return new HttpStatusCodeResult(404, msg);
            }

            topicPageViewModel.IsAuthenticatedUser = AuthenticationManager.User.Identity.IsAuthenticated;
            

            return View(topicPageViewModel);
        }

        /// <summary>
        /// Add comment inside topic's page
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult View(int id, string message) {
            if (!AuthenticationManager.User.Identity.IsAuthenticated) {
                return RedirectToAction("Index");
            }
            if (string.IsNullOrEmpty(message)) {
                string msg = "Something went wrong";
                return new HttpStatusCodeResult(500, msg);
            }
            var userProfileDTO = UserService.GetUserProfileByIdentityName(AuthenticationManager.User.Identity.Name);
            if (userProfileDTO == null) {
                string msg = "Something went wrong";
                errorLogger.Log("Authenticated user couldn't be found in DB", priority: 9);
                return new HttpStatusCodeResult(503, msg);
            }
            var topicAuthorUserProfileId = userProfileDTO.Id;

            var postDTO = new PostDTO()
            {
                Message = message,
                PostStatus = PostStatusDTO.Normal,
                TopicId = id,
                PostTime = DateTime.Now,
                UserProfileId = topicAuthorUserProfileId
            };

            try {
                postService.Add(postDTO);
            }
            catch (Exception ex) {
                string msg = "Something went wrong";
                errorLogger.Log(msg, priority: 9, exception: ex);
                return new HttpStatusCodeResult(503, msg);
            }

            return RedirectToAction("View", new { id = id });

        }

        // GET: Topic/Create
        [Authorize]
        public ActionResult Create()
        {
            var createTopicVM = new CreateTopicViewModel();

            // Get All Categories for category drop down list
            var categoriesDTOs = categoryService.GetAllCategories();
            createTopicVM.Categories = CategoryUtils.GetCategoriesListItems(categoriesDTOs);

            return View(createTopicVM);
        }

        // POST: Topic/Create
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateTopicViewModel model)
        {
            try
            {
                if (ModelState.IsValid) {
                    var topicDTO = Mapper.Map<CreateTopicViewModel, TopicDTO>(model);
                    var identityUser = UserService.GetUserProfileByIdentityName(AuthenticationManager.User.Identity.Name);
                    if (identityUser == null) {
                        string msg = "Something went wrong";
                        errorLogger.Log("Authenticated user couldn't be found in DB", priority: 9);
                        return new HttpStatusCodeResult(503, msg);
                    }
                    var topicAuthorUserProfileId = identityUser.Id;

                    var postDTO = new PostDTO()
                    {
                        Message = model.Message,
                        // TODO LATER if this topic from the new user, status -> awaiting moderation
                        // if post has external links(if not from ranked user) - moderation
                        PostStatus = PostStatusDTO.Normal,
                        PostTime = DateTime.Now,
                        UserProfileId = topicAuthorUserProfileId,
                    };
                    
                    var topicId = topicService.AddTopic(topicDTO, postDTO, topicAuthorUserProfileId);
                    return RedirectToAction("View", new { id = topicId });

                } else {
                    return View(model);
                }
            }
            catch(Exception ex)
            {
                string msg = "Something went wrong";
                errorLogger.Log("Authenticated user couldn't be found in DB", exception: ex);
                return new HttpStatusCodeResult(503, msg);
            }
        }


        // GET: Topic/Edit/5
        [AuthorizeInAnyRole(ForumUserRoles.SuperAdmin, ForumUserRoles.Admin, ForumUserRoles.TrustedModerator)]
        public ActionResult Edit(int? id)
        {
            string noTopicMsg = "No such topic exists";
            if (!id.HasValue) {
                return new HttpStatusCodeResult(404, noTopicMsg);
            }
            var entityID = id.Value;


            TopicDTO topicDTO = null;
            PostDTO topicsPrimaryPost = null;

            try {
                topicDTO = topicService.GetTopic(entityID);
                topicsPrimaryPost = postService.GetTopicsPrimaryPost(entityID);
            }
            catch (Exception ex) {
                errorLogger.Log("Error", priority: 9, url: "Topic/Edit", exception: ex);
                return new HttpStatusCodeResult(500, "Something went wrong");
            }
            if (topicDTO == null || topicsPrimaryPost == null) {
                return new HttpStatusCodeResult(404, "No such topic exists");
            }

            var model = Mapper.Map<TopicDTO, CreateTopicViewModel>(topicDTO);
            model.Categories = Util.CategoryUtils.GetCategoriesListItems(categoryService.GetAllCategories(), model.CategoryId);
            model.Message = topicsPrimaryPost.Message;
            
            
            return View(model);
        }

        // POST: Topic/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]

ThatForumCMS/Views/Shared/AdminNavMenu.cshtml
@model ThatForumCMS.Models.NavBarViewModel
@if (!(Model.IsModerator || Model.IsAdmin)) {
    return;
}
@* Show Manage tab in nav bar for admins and moders(not all links for thoose ones) *@
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            Manage
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li>@Html.ActionLink("Posts", "ShowPosts", "Admin")</li>
            <li>@Html.ActionLink("Topics", "List", "Topic")</li>

            @if (Model.IsAdmin) {

                <li>@Html.ActionLink("Categories", "Index", "Category")</li>
                <li>@Html.ActionLink("Users", "ShowUsers", "Admin")</li>
                <li>@Html.ActionLink("Error Logs", "ErrorLogs", "Admin")</li>
            }

        </ul>

    </li>

ThatForumCMS/Views/Shared/CategoryControlBtns.cshtml
@model int 
<div class="btn-group">
    @Html.ActionLink("Edit", "Edit", new { id = Model }, new { @class = "btn btn-primary" })
    <a href="#" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li>@Html.ActionLink("View", "View", new { id = Model }, new { id = "details" + Model })</li>
        <li>@Html.ActionLink("Delete", "Delete", new { id = Model })</li>
    </ul>
</div>

ThatForumCMS/Views/Shared/ChangePasswordPartial.cshtml
@model ThatForumCMS.Models.Users.ChangePasswordViewModel

<h4>Change password</h4>
<div id="changePassResult"></div>
<div class="changePassForm">
    @using (Ajax.BeginForm("ChangePassword", "Account", new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "changePassResult",
        LoadingElementId = "loader",
        OnComplete = "onChangePassComplete"
    }, new { @id= "regform" })) {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.CurrentPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrentPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrentPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NewPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    }

    <script>
        function onChangePassComplete(response) {
            $('#CurrentPassword').val('');    
            $('#NewPassword').val('');    
            $('#ConfirmPassword').val('');    
        }
    </script>
    @Scripts.Render("~/bundles/jqueryvalidation")
    @Scripts.Render("~/bundles/validationChangePassword")
</div>

ThatForumCMS/Views/Shared/LoginPartial.cshtml
@model ThatForumCMS.Models.Users.LoginViewModel



<div class="modal fade" id="loginModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style="padding:35px 50px;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4>Login</h4>
            </div>
            <div class="modal-body" style="padding:40px 50px;">


                @*//@using (Ajax.BeginForm("Login", "Account", new AjaxOptions { HttpMethod = "Post" })) {*@
                @using (Html.BeginForm("Login", "Account", FormMethod.Post)) {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.RemebmerMe, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="checkbox">
                                    <label>
                                        @Html.EditorFor(model => model.RemebmerMe)
                                    </label>
                                    @Html.ValidationMessageFor(model => model.RemebmerMe, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Login" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-danger btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
                <p>Not a member? @Html.ActionLink("Sign Up", "Register", "Account")</p>
                @*<p>Forgot <a href="#">Password?</a></p>*@
            </div>
        </div>

    </div>
</div>
<script>
        $(document).ready(function () {
            $("#loginLinkBtn").click(function () {
                $("#loginModal").modal();
            });
        });
</script>

ThatForumCMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Some interesting title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>  
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <style>
        .modal-header, .close {
            background-color: #d34615;
            color: white !important;
            text-align: center;
            font-size: 30px;
        }

        .modal-footer {
            background-color: #eeeeee;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("That Forum", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    
                    @Html.Action("NavBar", "Home")

                    @*if user signed in - show Profile tab*@
                    @if (User.Identity.IsAuthenticated) {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Profile
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Edit", "Edit", "Account")</li>
                                <li>@Html.ActionLink("Show", "Index", "Account")</li>
                            </ul>
                        </li>
                    }

                </ul>

                <ul class="nav navbar-nav navbar-right">
                    @{
                        var userName = Context.User.Identity.Name;
                    }
                    @if (string.IsNullOrEmpty(userName)) {
                        <li>
                            @*<a href="@Url.Action("Login", "Account")"><span class="glyphicon glyphicon-log-in"></span> Login</a>*@
                            <a href="#" id="loginLinkBtn">Login</a>
                    
                        </li>
                        <li><a href="@Url.Action("Register", "Account")"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                    } else {
                        <li><a href="@Url.Action("Logout", "Account")">Hi, @userName <span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                    }

                    
                    
                </ul>
            </div>

        </div>
    </div>


    <div class="container body-content">



        @RenderBody()
        <hr />

        @if (string.IsNullOrEmpty(userName)) {
            @Html.Partial("LoginPartial", new ThatForumCMS.Models.Users.LoginViewModel())

        }

        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

ThatForumCMS/Views/Shared/_patientList.cshtml
@model ThatForumCMS.Controllers.AccountController.AvatarVM
@if (Model != null) {
    @Html.DisplayFor(m=>m.Url)
}